server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/demo.mapper/*.xml

#spring配置
spring:
  application:
    name: springcloud-provider-hand_employees
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/mybatis?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/train?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: pyh903903

#eureka 的配置，服务注册到哪儿
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
    instance:
      instance-id: springcloud-provider-hand_employees # 修改eureka上默认描述信息


info:
  app.name: springcloud
  company.name: Hchier